# Generated by Django 6.0.6 on 2026-06-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Evento')),
                ('descripcion', models.TextField(verbose_name='Descripción del Evento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones o Notas Adicionales')),
                ('festividades', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora del Evento')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='eventos/principales/', verbose_name='Imagen Principal')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
