# Generated by Django 6.0.6 on 2026-06-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Lugar')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('rutas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rutas de Acceso / Dirección')),
                ('descripcion', models.TextField(verbose_name='Descripción del Lugar')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones o Notas Adicionales')),
                ('festividades', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Festividades')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='lugares/principales/', verbose_name='Imagen Principal')),
                ('galeria_fotos', models.ImageField(blank=True, null=True, upload_to='lugares/galeria/', verbose_name='Fotos de la Galería')),
                ('es_solo_adultos', models.BooleanField(default=False, verbose_name='¿Es exclusivo para adultos?')),
            ],
            options={
                'verbose_name': 'Lugar Turístico',
                'verbose_name_plural': 'Lugares Turísticos',
            },
        ),
    ]
